// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTemplate(arg1) {
  return window['go']['main']['App']['CreateTemplate'](arg1);
}

export function DiscardTemplate(arg1) {
  return window['go']['main']['App']['DiscardTemplate'](arg1);
}

export function GetKernelOverride() {
  return window['go']['main']['App']['GetKernelOverride']();
}

export function IntegrationSelfTestEnabled() {
  return window['go']['main']['App']['IntegrationSelfTestEnabled']();
}

export function OpenModel() {
  return window['go']['main']['App']['OpenModel']();
}

export function RecordIntegrationSelfTest(arg1) {
  return window['go']['main']['App']['RecordIntegrationSelfTest'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['main']['App']['SaveTemplate'](arg1);
}
