// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateTemplate(arg1:main.CreateTemplateRequest):Promise<main.PreviewResponse>;

export function DiscardTemplate(arg1:string):Promise<void>;

export function GetKernelOverride():Promise<main.KernelOverride>;

export function IntegrationSelfTestEnabled():Promise<boolean>;

export function OpenModel():Promise<main.ModelFile>;

export function RecordIntegrationSelfTest(arg1:main.IntegrationSelfTestResult):Promise<void>;

export function SaveTemplate(arg1:main.SaveTemplateRequest):Promise<main.SaveTemplateResponse>;
